repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/djlint/djlint
    rev: v1.36.4
    hooks:
      - id: djlint
        args: ["--lint", "--reformat"]
        files: "\\.html$"
