# Generated by Django 5.2.5 on 2025-08-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="instock",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
